# Generated by Django 4.2 on 2023-04-07 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('customer_address', models.CharField(max_length=150, verbose_name='Customer Address')),
                ('zip_code', models.CharField(max_length=100, verbose_name='Zip Code')),
                ('building', models.CharField(max_length=150, verbose_name='Building')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('state', models.CharField(max_length=150, verbose_name='State')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('total_qty', models.IntegerField(verbose_name='Total Quantity')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_user', to='users.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
